# Overwrites
printWidth: 120
useTabs: true

# Default values
tabWidth: 2
semi: true
singleQuote: false
quoteProps: 'as-needed'
jsxSingleQuote: false
trailingComma: 'es5'
bracketSpacing: true
bracketSameLine: false
arrowParens: 'always'

# rangeStart: 0
# rangeEnd: Infinity

# parser: undefined
# filepath: undefined
requirePragma: false
insertPragma: false

proseWrap: 'preserve'

htmlWhitespaceSensitivity: 'css'

vueIndentScriptAndStyle: false

endOfLine: 'lf'

embeddedLanguageFormatting: 'auto'
